package com.bignerdranch.android.shareddata.commands.clientModels.supportingModels;

public enum UpdateType {
    CHAT, PLAYER_ADDED, PLAYER_REMOVED, GAME, GAME_ADDED, GAME_REMOVED, INCREASED_PLAYER_COUNT, DECREMENT_PLAYER_COUNT,
    SCREEN_STATE, DISPLAY_ERROR, PLAYER_INFO, HAND_UPDATE, DECK_UPDATE, DRAW_DEST_CARDS, TURN_UPDATE, LAST_ROUND_NOTIFICATION, ROUTE_UPDATE
}
